name: hellblog
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  responsive_builder: ^0.6.0
  google_fonts: ^4.0.3
  progress_state_button: ^1.0.4
  url_strategy: ^0.2.0
  go_router: ^6.2.0
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  shared_preferences: ^2.1.0
  cloud_firestore: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/registration_page/
